server:
  port: 8123

spring:
  application:
    name: USER-SERVICE
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://103.87.128.78:32432/rtsp
    username: ENC(eILvi2aY5+xdtJeQNVgrnT5A/gzKH48C)
#    password: rtspUser@007
    password: ENC(R0NnTYpBh1BqqS4ZIfWcr/1yNmnyLORR)
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 20000 
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  signKey: s3cret
  validity: 3600000
  signAlgo: HS512

jasypt:
  encryptor:
#    password: s3cret
    algorithm: PBEWITHMD5ANDDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
springdoc:
  swagger-ui:
    path: /swagger-ui.html
